### ISSUE TITLE
__int128 is not supported on this target

### ISSUE THREAD

**Issue by aep** [quininer/rust-hacl-star#1]
looks like the fix is https://github.com/project-everest/hacl-star/issues/86

any opinion on how to implement that?

**Comment by aep** [comment]
it looks like there's an attempt to do it here
https://github.com/quininer/rust-hacl-star/blob/master/hacl-star-sys/build.rs#L11

but thats not correct.  cfg() is for the HOST not the target.

**Comment by quininer** [comment]
You are right, the target of `build.rs` is actually the host of project.

Sometimes this can be confusing. :(

**Comment by quininer** [comment]
Can you try to see if this branch works? https://github.com/quininer/rust-hacl-star/tree/fix32
